name: Test deployment

on:
  pull_request:
    branches:
      - test-copy-action

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Get changed files in docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v36
        with:
          files: docs
      - name: Copy changes to versioned docs if docs folder changed
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "One or more files in the docs folder has changed."
          echo "List all the files that have changed: ${{ steps.changed-files-specific.outputs.all_changed_files }}"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Check links
        run: yarn run remark --quiet --use remark-validate-links --use remark-lint-no-dead-urls ./docs
      - name: Test build website
        run: yarn build